### ISSUE TITLE
"Solid not detected" against Stackblitz demo on Chrome on Linux

### ISSUE THREAD

**Issue by lourot** [thetarnav/solid-devtools#266]
I have opened the [Stackblitz demo](https://stackblitz.com/edit/solid-devtools-demo?file=src%2Fmain.tsx) and followed the instructions:

```ts
// now to use the extension open the playground page in a new tab
// e.g. https://soliddevtoolsdemo-pd2g--5173.local-credentialless.webcontainer.io/
// open the devtools and a "Solid" panel should appear
// try refreshing if it doesn't work

// if you don't have the devools installed, here is the link:
// https://chrome.google.com/webstore/detail/solid-devtools/kmcfjchnmmaeeagadbhoofajiopoceel
```

![Screenshot from 2023-10-03 18-06-20](https://github.com/thetarnav/solid-devtools/assets/11795312/ff199911-1762-40d5-8eab-1fca9071ba86)

The extension only says "Solid not detected".  Other extensions are disabled. The console shows

```
Uncaught TypeError: O.createRoot is not a function
    at Hn (debugger.ts-2ca0ccc4.js:1:6771)
    at debugger.ts-2ca0ccc4.js:64:12559
```

Solid Devtools 0.27.7
Chrome 117.0.5938.132
Ubuntu 22.10

Any help appreciated, thanks a lot!

**Comment by AurelienLourot** [comment]
And after refreshing the page, I'm back at "Solid not detected".

**Comment by kauderk** [comment]
Problem at `"solid-devtools": "^0.27.1"` but fixed at `"solid-devtools": "^0.29.2"`, please update the [Stackblitz Demo](https://stackblitz.com/edit/solid-devtools-demo?file=src%2Fmain.tsx)

This interface must have changed the `createRoot` function location.

```js
var SolidApi = globalThis.SolidDevtools$$;
var solid_api_default = SolidApi;
...
...
var createInternalRoot = (fn, detachedOwner) => {
  InternalRootCount++;
  const r = solid_api_default.createRoot((dispose) => {
//                               ^^^
    solid_api_default.getOwner().isInternal = true;
    return fn(dispose);
  }, detachedOwner);
  InternalRootCount--;
  return r;
};
```

And here is the error
```js
debugger.ts-fea24b99.js:434 Uncaught TypeError: solid_api_default.createRoot is not a function
    at createInternalRoot (debugger.ts-fea24b99.js:434:31)
    at debugger.ts-fea24b99.js:1810:14
createInternalRoot @ debugger.ts-fea24b99.js:434
(anonymous) @ debugger.ts-fea24b99.js:1810
```

**Comment by apuatcfbd** [comment]
In `Solid Start (0.4.10)` project. The extension says Solid is detected & following shows up in console
```log
🚧 solid-devtools is in early development! 🚧
Please report any bugs to https://github.com/thetarnav/solid-devtools/issues
```
but there's no `Solid` tab in the (chrome) devtools

**Comment by aquaductape** [comment]
For the StackBlitz demo, you'll need to open the preview in new tab for extension to detect project.
<img width="671" alt="Screenshot 2024-04-19 at 1 48 37 PM" src="https://github.com/thetarnav/solid-devtools/assets/29286430/ad8f625a-9012-4294-9111-b6e648a768f6">

I was able to get extension to detect the project but the debugger tab in chrome devtools was missing. The solution to reveal the tab is making sure that your devtools package is the **exact same version number**  as the extension.

Currently the extension is `0.30.0`, so update the package to `0.30.0` without any version flags.
```json
"solid-devtools": "0.30.0"
```

Thankfully, recent version of extension reminds you of that. Here it tells you despite having the latest package version of devtools which is `0.30.1`, the extension expects to use `0.30.0`.

<img width="372" alt="Screenshot 2024-04-19 at 1 53 19 PM" src="https://github.com/thetarnav/solid-devtools/assets/29286430/ebe3a0e6-fb5b-4021-9603-ce915a8dec1e">

**Comment by thetarnav** [comment]
well I just updated the stackblitz demo with new version of packages and everything seems to be working fine

![image](https://github.com/user-attachments/assets/d7caa403-3c72-4d2f-8985-85a37f0dd4a9)

so I'm gonna close this, but feel free to open when there is more info or make a new issue
