### ISSUE TITLE
Dev tools not work 

### ISSUE THREAD

**Issue by mahmood601** [thetarnav/solid-devtools#284]
I have followed the instructions on getting started page and  devtools hasn't loaded 😕
I'm using kiwi brower on android with termux
Please help me!!

**Comment by thetarnav** [comment]
> kiwi brower on android with termux

were you able to find out why?
Those are not the tools I plan to spend time supporting right now, so unless someone familiar with those will be able to provide a way to integrate, you may have a better chance getting the [overlay package](https://github.com/thetarnav/solid-devtools/tree/main/packages/overlay#readme) to work.

**Comment by mahmood601** [comment]
I'm sorry for the late reply
The issue is with the active tab and this is the error 
```
AJRIPJTI-bb0fff76.js:15 solid-devtools Error: No data for active tab "1303990089"
    at getActiveTabData (background.ts-e29cce5f.js:99:12)
    at background.ts-e29cce5f.js:145:26
```
I think this is an issue with kiwi browser it opens dev tools with another tab different from the initial page
